### ISSUE TITLE
兄弟，同样在痛苦中，求交流

### ISSUE THREAD

**Issue by zishan11** [Qianqian-Wang-1997/2019Summer_SecureML#1]
我最近也观摩多遍，有些问题没有梳理清楚
1.比如作者采用的arithmetic sharing 方法是怎么贯穿其流程的，在随机梯度下降算法中他有体现一部分，但未给出证明（类似于线性同态性），我猜是引文可能提过。
2.有很多的细节和现实的接轨，并没有描述这些细节，引起我的一些疑惑，比如，data 通过秘密共享到S1和S2，然后两服务器的W也要秘密共享，training阶段w不都是随机值？还有two server 的output是给Client还是经过安全协议的交互将最终结果返回，当然前者是保障了隐私

也可能是我看的过程并不仔细，不知您是否有类似的疑惑，期待交流，我也在研究P-P ML方向，孤独啊！
我的电话：17604270376
邮箱：luanshijie@iie.ac.cn

**Comment by Qianqian-Wang-1997** [comment]
我也是一知半解，Prof. Zhang表示他知道一点哈哈
1. arithmetic sharing 是在offline/online multiplication triplets shares的使用的，用到加法乘法的基本上都用这个操作，19页的时候也有提到arithmetic sharing 和Yao's sharing的切换，（因为在质数域上bit计算困难，为了效率吧）。
2. training的时候是在原基础的w上加了随机值（噪声，第四页有提到）然后再进行训练的吧；这个我母鸡啊。

**Comment by zishan11** [comment]
谢谢哈，十分感动，我这两天找到一个类似于教材的国外资料，包含了Beaver triplets等sharing技术，里面有推导，我放在链接里吧https://www.nowpublishers.com/article/DownloadSummary/SEC-019。
容易理解的是，这些sharing相关的改进有两种目的：1.适用于不同场景的share design，Dr. Zhang 里的是2PC，他引文18里提到了多种情况。咱们写论文时也是根据场景进行设计。2. 尽可能地将大部分计算放在本地offline阶段，降低online cost。原理就是参照back propogation算法，咱不是在神经网络中经常用这个嘛，论文里也有相关描述。
我可能需要再次针对三类sharing：Beaver sharing、Yao sharing和Boolean sharing 做进一步的推导，不然还是无法深入理解Dr. Zhang 等大佬的设计思想。
您提到的training 时的随机值，我今天再看一下。
希望之后可以与您经常交流，目前这边就我一个人在做，理论基础和方案设计也没人可以讨论，再次谢谢您
最后，我想问一下，我昨天给Dr.  Zhang的农工那个邮箱发了邮件，请求张老师给与部分实验代码，期待能从代码中一探过程，但没有回信，您是怎么联系到张老师的，求指导

**Comment by Qianqian-Wang-1997** [comment]
我未来可能不会做这个方向，本身也没有密码学背景，学起来很累哈哈，但是我暑研是在他那里做的，有他的微信，tamu的邮箱他有在用，你看看过一阵他会不会回复你吧，加油（虽然这个方向真的很劝退.....）

**Comment by zishan11** [comment]
哦哦，羡慕啊，我同样难受中。。。加油兄弟！
